# Generated by Django 4.2.1 on 2023-06-01 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_tag_recipe_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="tag",
        ),
    ]
