# Generated by Django 4.2.1 on 2023-06-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_recipe_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="tag",
            field=models.ManyToManyField(to="core.tag"),
        ),
    ]
