# Generated by Django 4.2.1 on 2023-06-03 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_recipe_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="tag",
            new_name="tags",
        ),
    ]
